// Mocks generated by Mockito 5.4.6 from annotations
// in student_participation_app/test/data/services/data_import_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:student_participation_app/domain/entities/entities.dart' as _i4;
import 'package:student_participation_app/domain/repositories/i_class_repository.dart'
    as _i2;
import 'package:student_participation_app/domain/repositories/i_participation_repository.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [IClassRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIClassRepository extends _i1.Mock implements _i2.IClassRepository {
  MockIClassRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.SchoolClass>> watchClasses() => (super.noSuchMethod(
        Invocation.method(
          #watchClasses,
          [],
        ),
        returnValue: _i3.Stream<List<_i4.SchoolClass>>.empty(),
      ) as _i3.Stream<List<_i4.SchoolClass>>);

  @override
  _i3.Stream<List<_i4.Subject>> watchAllSubjects() => (super.noSuchMethod(
        Invocation.method(
          #watchAllSubjects,
          [],
        ),
        returnValue: _i3.Stream<List<_i4.Subject>>.empty(),
      ) as _i3.Stream<List<_i4.Subject>>);

  @override
  _i3.Future<int> addClass(
    String? name,
    String? teacher,
    String? room,
    String? schoolYear,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addClass,
          [
            name,
            teacher,
            room,
            schoolYear,
          ],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> updateClass(_i4.SchoolClass? schoolClass) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateClass,
          [schoolClass],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteClass(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteClass,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<List<_i4.Subject>> watchSubjects(int? classId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchSubjects,
          [classId],
        ),
        returnValue: _i3.Stream<List<_i4.Subject>>.empty(),
      ) as _i3.Stream<List<_i4.Subject>>);

  @override
  _i3.Future<int> addSubject(
    String? name,
    String? shortName,
    String? notes,
    int? classId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addSubject,
          [
            name,
            shortName,
            notes,
            classId,
          ],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> updateSubject(_i4.Subject? subject) => (super.noSuchMethod(
        Invocation.method(
          #updateSubject,
          [subject],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteSubject(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteSubject,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<List<_i4.Student>> watchStudents(int? classId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchStudents,
          [classId],
        ),
        returnValue: _i3.Stream<List<_i4.Student>>.empty(),
      ) as _i3.Stream<List<_i4.Student>>);

  @override
  _i3.Future<int> addStudent(
    String? firstName,
    String? lastName,
    String? photoPath,
    String? shortCode,
    int? classId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addStudent,
          [
            firstName,
            lastName,
            photoPath,
            shortCode,
            classId,
          ],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> updateStudent(_i4.Student? student) => (super.noSuchMethod(
        Invocation.method(
          #updateStudent,
          [student],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteStudent(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteStudent,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.SchoolClass>> getAllClasses() => (super.noSuchMethod(
        Invocation.method(
          #getAllClasses,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.SchoolClass>>.value(<_i4.SchoolClass>[]),
      ) as _i3.Future<List<_i4.SchoolClass>>);

  @override
  _i3.Future<List<_i4.Subject>> getAllSubjects() => (super.noSuchMethod(
        Invocation.method(
          #getAllSubjects,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Subject>>.value(<_i4.Subject>[]),
      ) as _i3.Future<List<_i4.Subject>>);

  @override
  _i3.Future<List<_i4.Student>> getAllStudents() => (super.noSuchMethod(
        Invocation.method(
          #getAllStudents,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Student>>.value(<_i4.Student>[]),
      ) as _i3.Future<List<_i4.Student>>);
}

/// A class which mocks [IParticipationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIParticipationRepository extends _i1.Mock
    implements _i5.IParticipationRepository {
  MockIParticipationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.Participation>> watchParticipations(
    int? studentId,
    int? subjectId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchParticipations,
          [
            studentId,
            subjectId,
          ],
        ),
        returnValue: _i3.Stream<List<_i4.Participation>>.empty(),
      ) as _i3.Stream<List<_i4.Participation>>);

  @override
  _i3.Future<List<_i4.Participation>> getParticipationsForSubject(
          int? subjectId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getParticipationsForSubject,
          [subjectId],
        ),
        returnValue:
            _i3.Future<List<_i4.Participation>>.value(<_i4.Participation>[]),
      ) as _i3.Future<List<_i4.Participation>>);

  @override
  _i3.Future<List<_i4.Participation>> getParticipationsForStudent(
          int? studentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getParticipationsForStudent,
          [studentId],
        ),
        returnValue:
            _i3.Future<List<_i4.Participation>>.value(<_i4.Participation>[]),
      ) as _i3.Future<List<_i4.Participation>>);

  @override
  _i3.Future<List<_i4.Participation>> getAllParticipations() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllParticipations,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.Participation>>.value(<_i4.Participation>[]),
      ) as _i3.Future<List<_i4.Participation>>);

  @override
  _i3.Future<int> addParticipation(
    int? studentId,
    int? subjectId,
    bool? isPositive, {
    String? note,
    int? behaviorId,
    int? sessionId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addParticipation,
          [
            studentId,
            subjectId,
            isPositive,
          ],
          {
            #note: note,
            #behaviorId: behaviorId,
            #sessionId: sessionId,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> deleteParticipation(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteParticipation,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<List<_i4.NegativeBehavior>> watchNegativeBehaviors() =>
      (super.noSuchMethod(
        Invocation.method(
          #watchNegativeBehaviors,
          [],
        ),
        returnValue: _i3.Stream<List<_i4.NegativeBehavior>>.empty(),
      ) as _i3.Stream<List<_i4.NegativeBehavior>>);

  @override
  _i3.Future<int> addNegativeBehavior(String? description) =>
      (super.noSuchMethod(
        Invocation.method(
          #addNegativeBehavior,
          [description],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> deleteNegativeBehavior(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteNegativeBehavior,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> startSession(
    int? subjectId, {
    String? topic,
    String? notes,
    String? homework,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startSession,
          [subjectId],
          {
            #topic: topic,
            #notes: notes,
            #homework: homework,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> endSession(int? sessionId) => (super.noSuchMethod(
        Invocation.method(
          #endSession,
          [sessionId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateSession(
    int? sessionId, {
    String? topic,
    String? notes,
    String? homework,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSession,
          [sessionId],
          {
            #topic: topic,
            #notes: notes,
            #homework: homework,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i4.ProtocolSession?> getActiveSession(int? subjectId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveSession,
          [subjectId],
        ),
        returnValue: _i3.Future<_i4.ProtocolSession?>.value(),
      ) as _i3.Future<_i4.ProtocolSession?>);

  @override
  _i3.Stream<_i4.ProtocolSession?> watchActiveSession(int? subjectId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchActiveSession,
          [subjectId],
        ),
        returnValue: _i3.Stream<_i4.ProtocolSession?>.empty(),
      ) as _i3.Stream<_i4.ProtocolSession?>);

  @override
  _i3.Future<List<_i4.ProtocolSession>> getSessionsForSubject(int? subjectId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessionsForSubject,
          [subjectId],
        ),
        returnValue: _i3.Future<List<_i4.ProtocolSession>>.value(
            <_i4.ProtocolSession>[]),
      ) as _i3.Future<List<_i4.ProtocolSession>>);
}
